### ISSUE TITLE
How to setup icon

### ISSUE THREAD

**Issue by Kikobeats** [siddharthkp/github-build#6]
<img width="383" alt="screen shot 2018-05-22 at 12 47 27" src="https://user-images.githubusercontent.com/2096101/40358151-a2c0880e-5dbe-11e8-9e45-b41d03051ca7.png">

I created an integration using this awesome project 🙂

Looks like the icon is recovering from the commit? or actually based on the repository author?

Could can we add custom icon support?

**Comment by siddharthkp** [comment]
The icon is decided by GitHub based on the `token` that's passed.

You can register your tool as a github application and set a custom icon

**Comment by Kikobeats** [comment]
Thanks!

**Comment by Kikobeats** [comment]
Can you oriented to me which permissions I need to have to have the similar effect to bundlesize?
https://bundlesize-store.now.sh/auth?code=81e603b34d274c898c0e

I think we can add this kind of information into the README as well.

**Comment by siddharthkp** [comment]
Well, If you're looking for the code, it's already in the bundlesize repo 😄 

Code: https://github.com/siddharthkp/bundlesize/blob/master/store/index.js#L39-L52

If you're looking for a library/service that makes it easier to replicate it, @mxstbr made one: https://github.com/mxstbr/micro-github

**Comment by Kikobeats** [comment]
Thanks for the comment!

I feel `micro-github` is an easy solution, thanks for that @mxstbr

This is the OAuth App that I created

<img width="776" alt="screen shot 2018-05-22 at 22 42 31" src="https://user-images.githubusercontent.com/2096101/40389157-e0b71012-5e11-11e8-87f9-46e23c785749.png">

However looks like the permissions for update status need to be written as well, not only read.

any idea? First time with GitHub API, I'm a totally newbie 😅
