### ISSUE TITLE
Generic way to get the url

### ISSUE THREAD

**Issue by Kikobeats** [siddharthkp/github-build#7]
The module expects pass an `url`, but I noted that the url is not provided by [ci-env](https://github.com/siddharthkp/ci-env).

Instead, I see at [bundlesize](https://github.com/siddharthkp/bundlesize/blob/accf79cf8db19e40b34c8a0f263626e7ef2b1fc6/src/reporter.js#L56) that the url is provided using an external service.

If I'm writing a similar library, can I  use the service? or url could be obtained combining different parameters from ci-env?

**Comment by siddharthkp** [comment]
Umm, I think you've got the url all wrong 🙂

`github-build` accepts a url that is opened when you click `Details` on the status. This is a url that you can provide.

The url isn't created by an external service or provided by ci-env. You can provide whatever url you want.

In the case of bundlesize, there is a prettier page to show the details of your pull request ([demo](https://bundlesize-store.now.sh/build?info=%7B%22files%22%3A%5B%7B%22maxSize%22%3A600%2C%22path%22%3A%22.%2Findex.js%22%2C%22size%22%3A197%2C%22master%22%3A197%7D%2C%7B%22maxSize%22%3A600%2C%22path%22%3A%22.%2Fsrc%2Ffiles.js%22%2C%22size%22%3A345%2C%22master%22%3A345%7D%5D%2C%22repo%22%3A%22siddharthkp%2Fbundlesize%22%2C%22branch%22%3A%22add-google-api-key%22%2C%22commit_message%22%3A%22Merge%20074abc5e43aef7b29b9925c171a358d7bdbe348f%20into%20688fb6c2a18563ef977fb20523c8bd9ad4866057%22%2C%22sha%22%3A%22074abc5e43aef7b29b9925c171a358d7bdbe348f%22%7D))

If you look at the URL, you'll find all the data is passed to [a page](https://github.com/siddharthkp/bundlesize/blob/master/store/views/build.pug) which formats and displays it.

**Comment by Kikobeats** [comment]
Thanks for the explanation.

I created a PR to illustrate how to get the url from Travis:
https://github.com/siddharthkp/ci-env/pull/17
